name: Deploy static content to Server

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "nginx"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: [self-hosted, oracle, kanduit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Copy resource to commit folder
      - name: Copy
        run: |
          commit_dir="/home/nginx/commits/${GITHUB_SHA::7}"
          if [ -d "$commit_dir" ]; then
            echo "Directory $commit_dir already exists. Deleting it."
            rm -rf "$commit_dir"
          fi
          echo "Copying files to $commit_dir."
          cp -r $(pwd) "$commit_dir"

      # Update symbolic link
      - name: Update symbolic link
        run: |
          target_path="/home/nginx/html-develop"
          
          if [ -L "$target_path" ]; then
            echo "Symbolic link already exists. Updating the link."
            ln -Tfs "$commit_path" "$target_path"
          else
            echo "Symbolic link does not exist. Creating a new link."
            ln -s "$commit_path" "$target_path"
          fi